name: task_manager
description: A modern task management app for gig workers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.19.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true